export const state = {
  root: null,
  screen: 'title',
  mode: 'Beginner',
  page: 1,
  ranking: { mode:'Beginner', loading:false, error:'', data:null },
  options: { crosshairColor:'#42a5f5', bgmVolume:50, seVolume:50, displayMode:'window' },
  filled: new Set(),
  cellColors: new Map(),
  selectedColor: '1',
  crossed: new Set(),
  drag: { active:false, mode:null, start:null, moved:false },
  hoverCell: null,
  timer: { limit:null, remaining:null, running:false, intervalId:null, expired:false, paused:false, pauseReason:null },
  modal: null,
  currentUser: null,
  userDataStatus: { storage:'localStorage', fileSave:false, filePath:null, lastLoad:null, lastSave:null, lastResult:'' },
  loginForm: { username:'', password:'', remember:false },
  authMessage: '',
  gameStatus: 'idle',
  game: null,
  playSession: null,
  solved: { Beginner:new Set(), Easy:new Set(), Normal:new Set(), Hard:new Set(), Endless:new Set() },
  error: ''
};
