export const state = {
  root: null,
  screen: 'title',
  mode: 'Beginner',
  page: 1,
  ranking: { mode:'Beginner', loading:false, error:'', data:null },
  news: { loading:false, loaded:false, error:'', items:[], selectedId:'' },
  admin: { loading:false, error:'', message:'', data:null, userQuery:'', roleFilter:'all', selectedUserId:'', rankingDifficulty:'all', rankingStage:'', rankingQuery:'', rankingSort:'time', selectedRankingId:'', deleteRequestStatus:'all', deleteRequestQuery:'', selectedDeleteRequestId:'' },
  selectPuzzles: {},
  selectLoaded: {},
  selectLoading: {},
  options: { crosshairColor:'#42a5f5', bgmVolume:50, seVolume:50, displayMode:'window' },
  filled: new Set(),
  cellColors: new Map(),
  selectedColor: '1',
  crossed: new Set(),
  drag: { active:false, mode:null, start:null, moved:false },
  hoverCell: null,
  timer: { limit:null, remaining:null, running:false, intervalId:null, expired:false, paused:false, pauseReason:null },
  hints: { limit:0, remaining:0 },
  boardZoom: 1,
  boardScroll: { left:0, top:0 },
  gamePanelCollapsed: null,
  minimapVisible: null,
  minimapZoom: null,
  minimapPosition: null,
  modal: null,
  currentUser: null,
  userDataStatus: { storage:'localStorage', fileSave:false, filePath:null, lastLoad:null, lastSave:null, lastResult:'' },
  accountDeleteRequest: { loading:false, data:null, error:'' },
  loginForm: { username:'', email:'', password:'', remember:false },
  authMessage: '',
  passwordRecovery: { active:false, forced:false, password:'', confirmPassword:'', error:'' },
  gameStatus: 'idle',
  game: null,
  playSession: null,
  solved: { Beginner:new Set(), Easy:new Set(), Normal:new Set(), Hard:new Set(), Endless:new Set() },
  error: ''
};
