-- Web Picross Ver2 Supabase schema
-- Apply this file in the Supabase SQL editor before 002_rls.sql.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text,
  role text not null default 'player' check (role in ('player', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.puzzles (
  id uuid primary key default gen_random_uuid(),
  difficulty text not null check (difficulty in ('beginner', 'easy', 'normal', 'hard', 'endless')),
  stage_no integer not null check (stage_no > 0),
  title text not null default '',
  width integer not null check (width > 0),
  height integer not null check (height > 0),
  color_mode text not null default 'mono' check (color_mode in ('mono', 'color')),
  palette jsonb not null default '[]'::jsonb,
  solution jsonb not null,
  thumbnail_path text,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (difficulty, stage_no)
);

create table if not exists public.user_progress (
  user_id uuid not null references public.profiles(id) on delete cascade,
  puzzle_id uuid not null references public.puzzles(id) on delete cascade,
  cleared boolean not null default false,
  best_clear_time_ms integer check (best_clear_time_ms is null or best_clear_time_ms >= 0),
  latest_clear_time_ms integer check (latest_clear_time_ms is null or latest_clear_time_ms >= 0),
  clear_count integer not null default 0 check (clear_count >= 0),
  fail_count integer not null default 0 check (fail_count >= 0),
  giveup_count integer not null default 0 check (giveup_count >= 0),
  hint_used_count integer not null default 0 check (hint_used_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, puzzle_id)
);

create table if not exists public.play_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  puzzle_id uuid not null references public.puzzles(id) on delete cascade,
  result text not null check (result in ('clear', 'fail', 'giveup')),
  play_time_ms integer not null default 0 check (play_time_ms >= 0),
  hint_used_count integer not null default 0 check (hint_used_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.ranking_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  puzzle_id uuid not null references public.puzzles(id) on delete cascade,
  difficulty text not null check (difficulty in ('beginner', 'easy', 'normal', 'hard', 'endless')),
  stage_no integer not null check (stage_no > 0),
  clear_time_ms integer not null check (clear_time_ms >= 0),
  created_at timestamptz not null default now(),
  unique (user_id, puzzle_id)
);

create index if not exists idx_puzzles_difficulty_stage_no on public.puzzles (difficulty, stage_no);
create index if not exists idx_puzzles_published on public.puzzles (is_published);
create index if not exists idx_user_progress_user_id on public.user_progress (user_id);
create index if not exists idx_user_progress_puzzle_id on public.user_progress (puzzle_id);
create index if not exists idx_play_history_user_created on public.play_history (user_id, created_at desc);
create index if not exists idx_play_history_puzzle_id on public.play_history (puzzle_id);
create index if not exists idx_ranking_records_difficulty_stage_time on public.ranking_records (difficulty, stage_no, clear_time_ms);
create index if not exists idx_ranking_records_user_id on public.ranking_records (user_id);
create index if not exists idx_ranking_records_puzzle_id on public.ranking_records (puzzle_id);

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_puzzles_set_updated_at on public.puzzles;
create trigger trg_puzzles_set_updated_at
before update on public.puzzles
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_progress_set_updated_at on public.user_progress;
create trigger trg_user_progress_set_updated_at
before update on public.user_progress
for each row execute function public.set_updated_at();

comment on table public.profiles is 'Supabase Auth user profile. Local admin/admin is development only and must not be used as production authentication.';
comment on table public.puzzles is 'Puzzle definitions migrated from data/*.json. solution stores mono/color answer cells as JSON.';
comment on table public.user_progress is 'Per-user aggregate progress migrated from user/*.json.';
comment on table public.play_history is 'Append-only play result history for clear, fail, and giveup events.';
comment on table public.ranking_records is 'Leaderboard records separated from local user JSON files.';
